### ISSUE TITLE
New URL Format

### ISSUE THREAD

**Issue by ScottBrenner** [jmyrberg/ASOT-Dashboards#1]
https://github.com/jmyrberg/ASOT-Dashboards/blob/0567159786381850ecdbaeee74bb92bdc1a79a8b/src/get_data.py#L30

The ASOT website uses a new URL format starting from episode 777: `'http://www.astateoftrance.com/episodes/a-state-of-trance-episode-' + episode_nb`

**Comment by ScottBrenner** [comment]
@jmyrberg Any plans to update this project?

**Comment by jmyrberg** [comment]
@ScottBrenner Unfortunately no plans, I am currently too busy with other stuff :( It would be interesting to see how the show has developed recently, though! If I were to do it, I would probably redo the whole thing with somewhat different tech stack anyways.

**Comment by ScottBrenner** [comment]
Alright, will close this issue. Have started https://github.com/ScottBrenner/asot-jupyter to see how the show has changed over time, check it out! https://scottbrenner.github.io/asot-jupyter/asot/bpm/2020/04/28/avg-bpm.html
